### ISSUE TITLE
GameObject containing ARSessionOrigin leads to performance problems if Transform not at Origin

### ISSUE THREAD

**Issue by MaxwellSpectar** [needle-mirror/com.unity.xr.arfoundation#1]
My team recently experienced an issue where the performance would drop down to less than 30 FPS in less than 5 minutes even if the app was only open and no menus were interacted with. The solution ended up moving the GameObject with ARSessionOrigin to Origin. Surprised there is not an in editor warning regarding this if it can cause such silent and violent performance problems. A warning or message in editor would be appreciated or forcing the GameObject to be at Origin if it has an ARSessionOrigin script attached, whichever would be more appropriate.

**Comment by marwie** [comment]
Hello, please [report this issue to Unity directly](https://support.unity.com/hc/en-us/articles/206336985-How-do-I-submit-a-bug-report-) as we are not officially associated with Unity so this will not reach the devs when reported from here unfortunately.
